DROP TABLE class_schedule_entries;
DROP TABLE invoice_items CASCADE;
DROP TABLE invoices CASCADE;
DROP TABLE utility_readings CASCADE;
DROP TABLE monthly_billings CASCADE;
DROP TABLE class_schedules CASCADE;
DROP TABLE room_preferences CASCADE;
DROP TABLE notification_recipients CASCADE;
DROP TABLE notifications CASCADE;
DROP TABLE maintenance_requests CASCADE;
DROP TABLE checkout_requests CASCADE;
DROP TABLE room_change_requests CASCADE;
DROP TABLE contracts CASCADE;
DROP TABLE equipment_items CASCADE;
DROP TABLE equipment_categories CASCADE;
DROP TABLE beds CASCADE;
DROP TABLE room_billing_cursors CASCADE;
DROP TABLE rooms CASCADE;
DROP TABLE room_types CASCADE;
DROP TABLE buildings CASCADE;
DROP TABLE staff CASCADE;
DROP TABLE students CASCADE;
DROP TABLE users CASCADE;
DROP FUNCTION initialize_room_cursor();
