CREATE INDEX ix_contracts_student_id_status ON contracts (student_id, status);
CREATE INDEX ix_contracts_bed_id_status ON contracts (bed_id, status);
CREATE INDEX ix_contracts_room_id_status ON contracts (room_id, status);
CREATE UNIQUE INDEX uq_contracts_open_student ON contracts (student_id) WHERE status IN ('PENDING','ACTIVE');
CREATE UNIQUE INDEX uq_contracts_active_bed ON contracts(bed_id) WHERE status = 'ACTIVE';
CREATE INDEX ix_room_change_requests_student_id_status ON room_change_requests (student_id, status);
CREATE INDEX ix_room_change_requests_status_created_at ON room_change_requests (status, created_at DESC);
CREATE UNIQUE INDEX uq_room_change_requests_pending_student ON room_change_requests (student_id) WHERE status = 'PENDING';
CREATE INDEX ix_checkout_requests_student_id_status_created_at ON checkout_requests (student_id, status, created_at DESC);
CREATE INDEX ix_checkout_requests_contract_id_status ON checkout_requests (contract_id, status);
CREATE INDEX ix_checkout_requests_room_id_status_created_at ON checkout_requests (room_id, status, created_at DESC);
CREATE UNIQUE INDEX uq_checkout_requests_pending_student ON checkout_requests (student_id) WHERE status = 'PENDING';
CREATE INDEX ix_maintenance_requests_student_id_status_created_at ON maintenance_requests (student_id, status, created_at DESC);
CREATE INDEX ix_maintenance_requests_room_id_status_created_at ON maintenance_requests (room_id, status, created_at DESC);
CREATE INDEX ix_maintenance_requests_assigned_staff_id_status ON maintenance_requests (assigned_staff_id, status);
CREATE INDEX ix_notifications_created_at ON notifications (created_at DESC);
CREATE INDEX ix_notifications_target_scope_created_at ON notifications (target_scope, created_at DESC);
CREATE INDEX ix_notification_recipients_student_id_is_read_created_at ON notification_recipients (student_id, is_read, created_at DESC);
CREATE INDEX ix_invoices_student_id_billing_period ON invoices (student_id, billing_period DESC);
CREATE INDEX ix_rooms_building_floor_number ON rooms(building_id, floor, room_number);
CREATE INDEX ix_rooms_room_type ON rooms(room_type_id);
CREATE INDEX ix_beds_room_status ON beds(room_id, status);
CREATE INDEX ix_equipment_items_room ON equipment_items(room_id);
CREATE INDEX ix_equipment_items_category ON equipment_items(category_id);
CREATE INDEX ix_monthly_billings_period ON monthly_billings(billing_period DESC);
